name: notter-backend

services:
  devcontainer:
    build:
      dockerfile: devcontainer.Dockerfile
      context: .
    volumes:
      - ../:/workspaces/notter-backend:cached
      - bash_history:/commandhistory
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    build:
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notter
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  bash_history:
  postgres:
