name: notter-backend

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - ../:/workspaces/notter-backend:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    build:
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notter
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
