name: Notter Backend CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-bookworm
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: notter
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipx
          pipx install "pdm~=2.15"
          pdm install
      - name: Install goose
        run: |
          set -e
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          if [ "$ARCH" = "aarch64" ];
          then
            ARCH=arm64
          fi
          VERSION="v3.20.0"
          GOOSE_URI="https://github.com/pressly/goose/releases/download/${VERSION}/goose_${OS}_${ARCH}"
          GOOSE_BIN="/usr/local/bin/goose"
          curl --silent --show-error --location --fail --location --output "${GOOSE_BIN}" "${GOOSE_URI}"
          chmod +x "${GOOSE_BIN}"
          echo "Goose was installed successfully"
      - name: Lint
        run: pdm run lint
      - name: Test coverage
        run: pdm run test-cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
