name: Notter Backend CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-bookworm
    steps:
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 16
          postgres_user: admin
          postgres_password: admin
          postgres_db: notter
          postgres_extensions: citext
          exposed_postgres_port: 5432
      - uses: actions/checkout@v4
      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('pdm.lock') }}
          path: .venv
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pdm~=2.15"
          pdm install --skip=:post
      - name: Install goose
        run: |
          curl -fsSL \
          https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
      - name: Lint
        run: pdm run lint
      - name: Test coverage
        run: pdm run test-cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
