name: Notter Backend CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_HOSTNAME: postgres
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: notter
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipx
          pipx install "pdm~=2.15"
          pdm install
      - name: Install goose
        run: |
          chmod +x .devcontainer/install-goose.sh
          sh .devcontainer/install-goose.sh
      - name: Lint
        run: pdm run lint
      - name: Test coverage
        run: pdm run test-cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
